---
title: "Milestone 2"
author: "Chloe Shawah"
date: "9/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Project 1: 2020 Dems on Twitter

This project involved extensive data collection because the author, Tanner Gildea, had to use Twitter's API to collect data on the tweeting patterns of 12 different 2020 candidates. This project has three main sections, "Summary Statistics," "Sentiment Analysis," and "Individual Key Words." The first, "Summary Statistics," allows readers to look at the volume and distribution of each candidate's tweets in faceted histograms, and even allows you reader to change the number of bins in the histograms. I think this is a very cool feature, and the faceted histograms are easy to look at and interpret. There is also a table including information about average number of retweets, favorites, etc., which provide some context to the effectiveness of the tweets in addition to the volume. The next section looked at the sentiment of the tweets using AFINN, NRC, and BING lexicons for sentiment analysis. I thought this was a really interesting section because it provided some insight about the content of the tweets, and it added a higher level of complexity to the project. The final section, "Key Words" allows you to search for specific words and see how many times each candidate mentions them and what other words they use when discussing it. I thought this project had lots of pros, including its 3-section structure, complexity, and clear visualizations. I honestly can't find any cons for this project... I thought it was great! If I had to be really nit-picky, I would say that I would have wanted to see the "emotions conveyed" expressed in percents of total tweets by a candidate so I can see the different breakdowns of emotions in a normalized way.

Project 2: Organ Donations and Transplants

This project by Shafi Rubbani investigates the differences in organ donations and transplants between countries and across 5 years. I liked how in the sections "Transplant Rates" and "Donation Rates," there is an option to view the number of donations/transplants per million people in the country. I feel like this is much more useful that just plotting the plain numbers per country, and I probably would have made it the default graph view. I also like how you can select the countries you want to compare on top of each other. One con is that for some countries in the "Transplant Proportions" section, there is an error message and no data table. I feel like these countries should not be options in the drop-down menu if there is no data on them, or perhaps an explanatory message would have been helpful. Another nit-picky con is that in the Summary page, the two bar charts use the same color scheme in the same order even though each color represents different countries between the two charts. This was a little difficult to look at, and I probably would have overriden the default colors in that case. After reading this project, I am curious about how transplant rate relates to donation rate, because in the Summary tab of the project, the country with the biggest increase in donations (Belarus) does not have the biggest increase in transplants (US). I find that very interesting!
